#!/usr/bin/with-contenv bash
cd "${HOME}"
exec /opt/conda/bin/jupyter lab \
  --notebook-dir="${HOME}" \
  --ip=0.0.0.0 \
  --no-browser \
  --allow-root \
  --port=8888 \
  --LabApp.token="" \
  --LabApp.password="" \
  --LabApp.allow_origin="*" \
  --LabApp.base_url="${NB_PREFIX}" \
  --LabApp.authenticate_prometheus=False