#
# Makefile
#

VERSION ?= $(shell ../utils/get-version.sh)
COMMIT_ID := $(shell git rev-parse HEAD)

IMAGE_PREFIX ?= ghcr.io/takedalab
IMAGE_NAME ?= $(shell basename ${PWD})
$(warning Image: $(IMAGE_PREFIX)/$(IMAGE_NAME):$(VERSION))

help: ## Show this help
	@echo "Help"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "    \033[36m%-20s\033[93m %s\n", $$1, $$2}'

.PHONY: default
default: help

.PHONY: build
build:	## Build an image
	DOCKER_BUILDKIT=1 docker build -t $(IMAGE_PREFIX)/$(IMAGE_NAME):$(VERSION) .

.PHONY: publish
publish:    ## Publish an image
	docker push $(IMAGE_PREFIX)/$(IMAGE_NAME):$(VERSION)